name: Laravel CI/CD

on:
  push:
    branches: [ main ] # Only push to Docker Hub when merging to main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: cars_liberty
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pdo_mysql, bcmath, gd

      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run Tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_DATABASE: cars_liberty
        run: |
          php -r "copy('.env.example', '.env');"
          php artisan key:generate
          php artisan migrate --force
          php artisan test

  # NEW JOB: DEPLOY TO DOCKER HUB
  push-to-dockerhub:
    needs: laravel-tests # Only runs if tests pass!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Replace 'your_username/repo' with your actual info
          tags: ${{ secrets.DOCKER_USERNAME }}/cars-liberty-app:latest